### ISSUE TITLE
Pip package MySQL-python installation fails because mysql_config is missing

### ISSUE THREAD

**Issue by rageshkrishna** [dry-dock/u14pytpls#7]
```
  Downloading MySQL-python-1.2.5.zip (108kB)
    Complete output from command python setup.py egg_info:
    sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "", line 20, in 
      File "/tmp/pip-build-ujOk2z/MySQL-python/setup.py", line 17, in 
        metadata, options = get_config()
      File "setup_posix.py", line 43, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 25, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found
```

**Comment by rageshkrishna** [comment]
Fixed by https://github.com/dry-dock/u14pytpls/pull/8
